spring.application.name=zenvora-backend
spring.datasource.url=jdbc:mysql://localhost:3306/zenvora
spring.datasource.username=root
spring.datasource.password=Poornimaa@16
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081